### ISSUE TITLE
Any progress on this? 

### ISSUE THREAD

**Issue by msestak** [elcamlost/perl-DBD-ClickHouse#1]
Hi,

I'm using Clickhouse and I was searching for a DBD driver for it from Perl. If you wrote some code in this direction I would gladly test it.

**Comment by elcamlost** [comment]
Helo!

We did some benchmarks and found clickhouse suitable for our case, but a 
lot of other work stopped my progress. So for now I wrote nothing, sorry ((

14.07.16 13:43, Martin Sebastijan Šestak пишет:

**Comment by elcamlost** [comment]
Finally, I released first version.
